### ISSUE TITLE
Making index.zul the default display page for a Spring Boot web app?

### ISSUE THREAD

**Issue by davoutuk** [zkoss-demo/zk-spring-boot#1]
HI,

Using your ZK Spring Boot code,  how would I make an 'index.zul' file the default resource opened by a Spring Boot web app?

**Comment by dirkdeyne** [comment]
@davoutuk 

1. create your **index.zul** in **src\main\resources\web\zul**
2. add you own Spring controller

```java
 package zk.springboot.controller;

 import org.springframework.stereotype.Controller;
 import org.springframework.web.bind.annotation.RequestMapping; 

 @Controller 
 public class YourController {

   @RequestMapping("/")
   public String home() {
	return "redirect:/index.zul";
   }

 }
```
done

**Comment by cor3000** [comment]
I agree this is clearly standard spring-mvc topic and not a zk-integration issue
